name: Build & Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Explotion80
          password: ${{ secrets.SIMPLE_WEBSITE }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/explotion80/simple-website/simple-website:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/explotion80/simple-website/simple-website:latest
